
<?php $_order = $this->getOrder() ?>

<table cellspacing="0" cellpadding="0" border="0"  width="600"  style="border:1px solid #bebcb7; background:#fff;">
    <thead>
        <tr>
            <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px"><font size="2"><?php echo $this->__('Item') ?></font></th>
            <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px"><font size="2"><?php echo $this->__('Sku') ?></font></th>
            <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px"><font size="2"><?php echo $this->__('Price') ?></font></th>
            <th align="center" bgcolor="#d9e5ee" style="padding:3px 9px"><font size="2"><?php echo $this->__('Qty') ?></font></th>
            <th align="right" bgcolor="#d9e5ee" style="padding:3px 9px"><font size="2"><?php echo $this->__('Subtotal') ?></font></th>
        </tr>
    </thead>

    <?php $i=0; foreach ($_order->getAllItems() as $_item): ?>
    <?php if($_item->getParentItem()) continue; else $i++; ?>
    <tbody<?php echo $i%2 ? ' bgcolor="#eeeded"' : '' ?>>
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>
    <?php endforeach; ?>

    <tbody>
       <?php echo $this->getChildHtml('order_totals') ?></font>
    </tbody>
</table>

<br />

<table cellspacing="0" cellpadding="0" border="0"  width="600" style="border:1px solid #bebcb7; background:#fff;">
    <thead>
        <tr>
            <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px"><strong><font size="2"><?php echo $this->__('Gift Message for this Order') ?></font></strong></th>
        </tr>
    </thead>

    <tbody>
        <?php if($_order->getGiftMessageId() && $_giftMessage = $this->helper('giftmessage/message')->getGiftMessage($_order->getGiftMessageId())): ?>
        <tr>
            <td colspan="4" align="left" style="padding:3px 9px" width="620">
            <strong><?php echo $this->__('From:'); ?></strong> <?php echo $this->htmlEscape($_giftMessage->getSender()) ?>
            <br /><strong><?php echo $this->__('To:'); ?></strong> <?php echo $this->htmlEscape($_giftMessage->getRecipient()) ?>
            <br /><strong><?php echo $this->__('Message:'); ?></strong><br /> <?php echo $this->htmlEscape($_giftMessage->getMessage()) ?>
            </td>
        </tr>
        <?php endif; ?>
    </tbody>

</table>
