<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/glider.js') ?>"></script>


<div id="slider">
<div class="slidercontrolwr">
<div class="slidercontrol"><a class="active" title="Slide 1" href="#section1">1</a> <a title="Slide 2" href="#section2">2</a> <a title="Slide 3" href="#section3">3</a></div>
</div>
<div class="scroller">
<div class="content">
<div id="section1" class="sectionslide"><img src="<?php echo $this->getSkinUrl('images/home_left.gif') ?>" alt="" /></div>
<div id="section2" class="sectionslide"><a href="#"><img src="<?php echo $this->getSkinUrl('images/home_left.gif') ?>" alt="" /></a></div>
<div id="section3" class="sectionslide"><a href="#"><img src="<?php echo $this->getSkinUrl('images/home_left.gif') ?>" alt="" /></a></div>
</div>
</div>
</div>
<script type="text/javascript">// <![CDATA[
					var my_glider = new Glider('slider', {duration:0.5, autoGlide: true, frequency: 4, initialSection: 'section1'});
				// ]]></script>
				
				
<img src="<?php echo $this->getSkinUrl('images/slider-wenzi.jpg') ?>">