<?php if ($this->getQuote()->isVirtual()) : return; endif; ?>
<div id="shipping-method" class="firecheckout-section">
    <div class="block-title" id="billing-shipping-title"><span><?php echo $this->__('Shipping Method') ?></span></div>
	<ul id="billing-shipping-content">
    <div id="checkout-shipping-method-load">
        <?php echo $this->getChildHtml('available') ?>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var shippingMethod = new ShippingMethod('shipping-method');
    //]]>
    </script>
	
	
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
        
    </div>
	</ul>
</div>
