<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>
<?php
	$customerId = Mage::getModel('customer/session')->getCustomerId();
	$customer = Mage::getModel('customer/customer')->load($customerId);
	$customerPoints = Mage::getModel('rewardpoints/account')
		->load($customerId);
		
?>
<div class="dash-pointer">
<!--<?php //echo $this->__('Total Accumulated Points') ?>: <?php //echo sprintf('%d', $customerPoints->getPointsReceived()); ?>
<br/>
<?php //echo $this->__('Your Points') ?>: <?php //echo sprintf('%d', $customerPoints->getPointsCurrent()); ?>
<br/>
<?php //echo $this->__('Total Points Spent') ?>: <?php //echo sprintf('%d', $customerPoints->getPointsSpent()); ?>
<br/>
<?php //echo $this->__('Points waiting for validation') ?>: <?php //echo sprintf('%d', $customerPoints->getPointsWaitingValidation()); ?>
<br/>-->
<?php echo $this->__('新可用积分') ?>: <?php echo sprintf('%d', $customer->getAvailablePoints()); ?>
<br/>
<?php echo $this->__('待验证积分') ?>: <?php echo sprintf('%d', $customer->getPendingPoints()); ?>
</div>




