<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>
<div class="page-head">
    <h3><?php echo $this->__('My Dashboard') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('hello') ?>
<?php echo $this->getChildHtml('top') ?>


<div class="box-account ad-account-info">
    <div class="box-head">
        <h2><?php echo $this->__('Account Information') ?> <a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('修改') ?></a></h2>
    </div>
    <?php echo $this->getChildHtml('info') ?>
    <?php //echo $this->getChildHtml('address') ?>
</div>
<div class="box-account aw-points">
	<div class="box-head">
		<h2><?php echo $this->__('Points') ?></h2>
	</div>
	<?php echo $this->getChildHtml('points') ?>
</div>


<?php echo $this->getChildHtml('info1') ?>
<?php echo $this->getChildHtml('info2') ?>