<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>

 


 
<div class="page-head">
    <h3><?php echo $this->__('Reward points') ?></h3>
</div>

<?php
	$customerId = Mage::getModel('customer/session')->getCustomerId();
	$customer = Mage::getModel('customer/customer')->load($customerId);
	$customerPoints = Mage::getModel('rewardpoints/account')
		->load($customerId);
		
?>


<div class="dash-pointer">
<?php echo $this->__('新可用积分') ?>: <?php echo sprintf('%d', $customer->getAvailablePoints()); ?>
<br/>
<?php echo $this->__('待验证积分') ?>: <?php echo sprintf('%d', $customer->getPendingPoints()); ?>
</div>
 <div class="dash-ds"><h2>亲爱的希思黎会员，如果您想查询您积分获取和使用的详细信息，请拨打我们的会员尊享热线:400-820-8139</h2></div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>


<?php $_points = $this->getPoints();?>
<?php if($_points->getSize()): ?>
<div style="display:none;">
<?php echo $this->getPagerHtml() ?>

<table cellspacing="0" class="data-table" id="reward-points-table">
    <thead>
        <tr>
            <?php ?><th><?php echo $this->__('Type of point') ?></th><?php ?>
            <th><?php echo $this->__('Points added') ?></th>
            <!--<th><?php echo $this->__('Points used') ?></th>-->
            <th><?php echo $this->__('Obtention date') ?></th>
            <th><?php echo $this->__('Valid until') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_points as $_point): ?>
            <tr>
                <td>
                    <?php if($_point->getRewardpoints_referral_id()): ?>
                        <?php echo $this->__('Referral points'); ?>
                        <?php $order = Mage::getModel('sales/order')->loadByIncrementId($_point->getOrder_id());?>
                        <br />
                        <?php echo $this->__('Referral order state : %s',$this->__($order->getState()));?>
                    <?php elseif ($_point->getOrder_id() < 0):?>
                        <?php echo $this->__('Regist Gift'); ?>
                    <?php else: ?> 
                        <a href=""><?php echo $this->__('Order : %s', $_point->getOrder_id()); ?></a>
                        <?php $order = Mage::getModel('sales/order')->loadByIncrementId($_point->getOrder_id());?>
                        <br />
                        <?php echo $this->__('Order state : %s',$this->__($order->getState()));?>
                    <?php endif; ?>
                </td>
                <td><?php echo $_point->getPoints_current() ?></td>
                <?php /*?><?php echo $_point->getPoints_spent() ? $this->__('yes') : $this->__('no') ?><?php */?>
                <!--<td class="points-spent">
				<?php //if($_point->getPoints_spent()){ ?>
				<?php //echo $_point->getPoints_spent() ?></td>
				<?php //}else{ ?>
				<?php //echo 0 ?>
				<?php //} ?>-->
                <td><?php if ($_point->getDate_start() != ""): echo $this->formatDate($_point->getDate_start(), 'short'); endif; ?></td>
                <td><?php if ($_point->getDate_end() != ""): echo $this->formatDate($_point->getDate_end(), 'short'); endif; ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php echo $this->getPagerHtml() ?>
<?php else: ?>
    <p><?php echo $this->__('You don\'t have any recorded points.'); ?></p>
<?php endif ?>
</div>
