<?php
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>

<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()):?>


<p class="product-image-zoom2">

   <?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';

    ?>
<a class="MagicZoom" id="mz1"  rel="opacity: 50;zoom-position: right" title="<?php echo $this->getImageLabel();?>">


<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(238,272); ?>" />
  
</a>

</p>
<?php else: ?>
 
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(236,270).'" alt="'.$this->htmlEscape($_product->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
		$zoom_img = $this->helper('catalog/image')->init($_product, 'image');
    ?>

<?php endif; ?>

