<?php
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>

<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()):?>


<p class="product-image-zoom2">

   <?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
       // echo $_helper->productAttribute($_product, $_img, 'image');
    	//$zoom_img = $this->helper('catalog/image')->init($_product, 'image')->resize(285);
    ?>
<a class="MagicZoom" id="mz1"  rel="opacity: 50;zoom-position: right" title="<?php echo $this->getImageLabel();?>">


<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(285); ?>" />
   <!-- <div class="MagicZoomBigImageCont" style="overflow: hidden; width: 300px; height: 300px; z-index: 100; visibility: hidden; position: absolute; top: -10000px; left: 215px;">
        	<div style="padding: 3px; position: relative; z-index: 10; left: 0px; top: 0px;" class="MagicZoomHeader">Akio Dresser</div> 
        	
        </div>
        <div class="MagicZoomLoading" style="position: absolute; visibility: hidden; display: block; text-align: center; left: 19.5px; top: 75px;">Loading Zoom, please wait<br />
		<img border="0" alt="Loading Zoom, please wait" src="<?php echo $this->getSkinUrl('images/mz_loading.gif') ?>"/></div>
        <div style="z-index: 10; visibility: hidden; position: absolute; opacity: 0.5; width: 186px; height: 174px;" class="MagicZoomPup"></div>
		<div style="color: rgb(204, 204, 204); font-size: 10px; font-family: Tahoma; position: absolute; width: 100%; text-align: center; left: 0px; top: 280px;"/></div>-->
</a>

</p>
<!--<p class="a-center" id="track_hint"><?php //echo $this->__('Double click on above image to view full picture') ?></p>

<div class="image-zoom" id="track_outer">
    <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
    <div id="track">
        <div id="handle"></div>
    </div>
    <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
</div>-->
<script type="text/javascript">
   /* Event.observe(window, 'load', function() {
        product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
    }); */
</script>
<?php else: ?>
 
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(285).'" alt="'.$this->htmlEscape($_product->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
		$zoom_img = $this->helper('catalog/image')->init($_product, 'image');
    ?>

<?php endif; ?>
<?php /*if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
    <h4><?php echo $this->__('More Views') ?></h4>
    <ul>
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <li>
            <!--<a href="#" onclick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=50,top=50,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;">
			<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
			</a>-->
			<a rev="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(285); ?>" style="outline-color: -moz-use-text-color; outline-style: none; outline-width: 0pt;" rel="mz1" href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>">
			<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
			</a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif;*/ ?>
