<form id="co-shipping-method-form" action="">
	<div class="left-shipping-method" >
    <div id="checkout-shipping-method-load">
        <?php //echo $this->getChildHtml('available') ?>
		<div class="left">运费：<input type="radio" name="1" id="1001">￥10元</input></div>
    </div>
	<!-- Add Package Class -->

	<!--<div class="pack-time">
	   <div><strong>选择包装类型</strong></div>
		   <ul>
			   <li><input type="radio" checked="checked" id='package1' value="normal" name="package"/>
					 <label for="package1">尊享心意礼盒(普通版)</label>
			   </li>
			   <li><input type="radio" id='package2' value="luxury" name="package"/>
					 <label for="package2">尊享心意礼盒(限量版)</label>
			   </li>
							   
		   </ul>
	</div>-->
	
	<div id="pack-time">
			<?php $_helper = $this->helper('catalog/output'); ?>
				<?php
						$_productCollection_1 = Mage::getModel('catalog/product')->getCollection()
									->addCategoryFilter(Mage::getModel('catalog/category')->load(296),true)
									->addAttributeToFilter('visibility',2)
									->addAttributeToSelect('*')
									->addAttributeToSort('entity_id', 'ASC')
									->setPageSize(2)
									->setCurPage(1)
									->load();

						Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($_productCollection_1);
						Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($_productCollection_1);
					?>
	
	
		<?php //var_dump($_productCollection_1); 
		//exit;
		
		?>
		<div class="pack-time-detial">
			 <div class="alert">
			   选择包装类型：
			 </div>
			 
			 <?php $i=0; foreach ($_productCollection_1 as $_product): ?>
			
			 <div class="Radio-contan">
			  <input type="radio" name="choosepackage" class="packageradio" checked="checked" value="<?php echo $_product->getId(); ?>" /><span class="radioName"><?php echo $this->htmlEscape($_product->getName()) ?></span>
			 </div>
			 
			<?php endforeach ?>
		</div>
	</div>
	
	
	<!-- End Add -->
	</div>
	
<div class="shipping-time">
       <div><strong>选择送货时间</strong></div>
       <ul>
       <li><input type="radio" checked="checked" id='time1' value="all" name="shipping_time"/>
             <label for="time1">工作日、双休日与假日均可送货</label>
       </li>
       <li><input type="radio" id='time2' value="holidays" name="shipping_time"/>
             <label for="time2">仅双休日、假日送货(工作日不用送货)</label>
       </li>
       <li><input type="radio"  id='time3' value="workdays" name="shipping_time"/>
             <label for="time3">仅工作日送货(双休日、假日不用送货)</label>
             <div class="shipping-tips" style="padding-left:16px;color:#999;">写字楼/商用地址客户选择</div>
       </li> 
       <li><input type="radio"  id='time4' value="nights" name="shipping_time"/>
	   
             <label for="time4">学校地址(该地址白天没人，请尽量安排其他时间送货)</label>
             <div class="shipping-tips" style="padding-left:16px;color:#999;">特别安排可能超出预算送货天数</div>
       </li>                      
       </ul>
</div>
<div class="clearer"></div>
    
    
    <script type="text/javascript">
    //<![CDATA[
        var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
        jQuery("input[name='shipping_time']").change(

function()
{


if (jQuery("input[name='shipping_time']:checked").val()){
         $('deliveryTime').value = jQuery("input[name='shipping_time']:checked").val();
}
}
);   
        
        
    //]]>
    </script>
    <div id="onepage-checkout-shipping-method-additional-load">
        <?php echo $this->getChildHtml('additional') ?>
    </div>
    <div class="buttons-set" id="shipping-method-buttons-container">
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button" onclick="shippingMethod.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="shipping-method-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</form>
