<?php
function SendEmail($customer, $_order) { 
/*** start edm ***/
$SoapClient = new SoapClient("http://app.focussend.com/webservice/FocusSendWebService.asmx?WSDL",array('trace' => 1));
$FocusUser   = new StdClass;
$FocusUser->Email="arvatoservices@bertelsmann.com.cn";
$FocusUser->Password=sha1("EDM$%^456"); 

$FocusEmail=new StdClass;

//邮件内容谨慎修改

$FocusEmail->Body="
<table width='635px' cellspacing='0' cellpadding='0' border='0'>
<tr>
<td>
<a href='http://sisley.com.cn'>
<img src='http://www.sisley.com.cn/skin/frontend/default/default/images/logo_email.gif' alt='sisley_logo' border='0'/>
</a>
</td>
</tr>
<tr>
<td>
<table  style='text-align: center;' cellspacing='0' cellpadding='0' border='0' width='635px'>
<tr style='background:#AAAAAA; color:white; ' height='1px'>
<td style='width:105px; border-right:1px solid white;'><a href='http://www.sisley.com.cn/news.html' ><font size='2'>希思黎最新动态</font></a></td>
<td style='width:105px; border-right:1px solid white;'><a href='http://www.sisley.com.cn/about-sisley.html'><font size='2'>关于希思黎</font></a></td>
<td style='width:105px; border-right:1px solid white;'><a href='http://www.sisley.com.cn/skincare.html'><font size='2'>护肤系列</font></a></td>
<td style='width:105px; border-right:1px solid white;'><a href='http://www.sisley.com.cn/color.html'><font size='2'>彩妆系列</font></a></td>
<td style='width:105px; border-right:1px solid white;'><a href='http://www.sisley.com.cn/perfume.html'><font size='2'>香水系列</font></a></td>
<td style='width:105px; border-right:1px solid white;'><a href='http://www.sisley.com.cn/man.html'><font size='2'>男士系列</font></a></td>
</tr>
</table>
</td>
</tr>
<tr>
<td>
<table width='635px'>
<tr>
<td valign='top' width='380px'>
<br />
<font size='2'>亲爱的".$CustomerName = $customer->getFirstname().$customer->getLastname()."，，</font><br /><br />
<font size='2'>感谢您在希思黎官方购物网站<a href='http://www.sisley.com.cn'>www.sisley.com.cn</a>购买希思黎产品。<br /><br />
您的订单：".$_order."，已确认您已收到并已处理完毕。<br /><br />
您此次的购买积分已激活为有效积分。您可以使用有效积分兑换<br />
喜爱的礼品。详情查看<a href='www.sisley-beauty.com.cn'>积分规则</a>：您可以通过链接登陆希思黎至<br />
臻坊社区查询您的积分并兑换相应的礼品<br /><br />
<a href='www.sisley-beauty.com.cn'><img  align='left' src='http://www.sisley.com.cn/skin/frontend/default/default/images/jfcx.jpg'  border='0'/></a><br /><br />
<a href='www.sisley-beauty.com.cn'>http://www.sisley-beauty.com.cn/</a><br /><br />
同时，为了更好地为希思黎客人提供尊贵服务，我们希望占用您<br />
几分钟的时间，完成希思黎网上购物体验售后问卷。我们将针对<br />
您的意见，对我们的工作进行改进。<br />
为感谢您为我们提供的宝贵建议，我们希思黎至臻坊社区将赠送<br />
您1000积分予以奖励！<br /><br />
完成问卷调查，获得机会100%！<br />
<a href='http://www.sisley.com/questionnaire?id=".$_order."'><img  align='left' src='http://www.sisley.com.cn/skin/frontend/default/default/images/ljcjdtl.jpg' border='0' /></a><br /><br />
<br />
</font>
</td>
<td>
<img src='http://www.sisley.com.cn/skin/frontend/default/default/images/email-bg.png' width='241' height='332' border='0' /></td>
</tr>

<br />
</table>
</td>
</tr>
<tr>
<td >
<font size='2'>
<br /><br />欢迎您再次到希思黎官方网站暨网上商城，祝您购物愉快！<br /><br /></font>
</td>
</tr>
<tr style='background:#E0E0E0;'>
<td width='635px'>
	<table cellspacing='0' cellpadding='0' border='1' width='635px'>
	<tr><td style='background:#e0e0e0' align='left'>
		<font size='2'>希思黎最受欢迎产品</font>
	</td></tr>
	</table>
</td></tr>
<tr>
<td>
<table>
<tr>
<td width='15px'>
</td>

<td>
	<table cellspacing='0' cellpadding='0' border='0'>
		<tr><td align='center' width='130px' >
			<a href='http://www.sisley.com.cn/114100.html'><img src='http://www.sisley.com.cn/skin/frontend/default/default/images/email-img/全能乳液.jpg' alt='全能乳液'  width='100px' height='100px' border='0' /></a>
		</td>
		</tr>
		<tr><td align='center' width='130px' >
			<a href='http://www.sisley.com.cn/114100.html'><font size='2'>全能乳液</font></a><br />
			<a href='http://www.sisley.com.cn/114100.html'><font size='2'>125ml - ￥1,520.00</font></a>
		</td></tr>
	</table>
</td>
<td width='15px'>
</td>
<td>
	<table cellspacing='0' cellpadding='0' border='0'>
	<tr><td align='center' width='130px'>
		<a href='http://www.sisley.com.cn/154000.html'><img src='http://www.sisley.com.cn/skin/frontend/default/default/images/email-img/致臻夜间修复精华露.jpg' alt='致臻夜间修复精华露' width='100px' height='100px' border='0' /></a>
	 </td></tr>
	 <tr><td width='130px' align='center' >
		<a href='http://www.sisley.com.cn/154000.html'><font size='2'>致臻夜间修复精华露</font></a><br />
		<a href='http://www.sisley.com.cn/154000.html'><font size='2'>50ml - ￥5,000.00</font></a>
	</td></tr>
	</table>
</td>
<td width='15px'>
</td>
<td>
<table cellspacing='0' cellpadding='0' border='0'><tr><td align='center' width='130'>
<a href='http://www.sisley.com.cn/126600.html'><img src='http://www.sisley.com.cn/skin/frontend/default/default/images/email-img/126600.jpg' alt='赋活水润保湿霜' width='100' height='100' border='0'/></a>
</td></tr>
<tr><td align='center' width='130' >
<a href='http://www.sisley.com.cn/126600.html'><font size='2'>赋活水润保湿霜</font></a><br />
<a href='http://www.sisley.com.cn/126600.html'><font size='2'>40ml - ￥1,500.00</font></a>
</td></tr>
</table>
</td>
<td width='15px'>
</td>
<td>
	<table cellspacing='0' cellpadding='0' border='0'><tr><td align='center' width='130px'>
	<a href='http://www.sisley.com.cn/150000.html'><img src='http://www.sisley.com.cn/skin/frontend/default/default/images/email-img/抗皱活肤驻颜霜.jpg' alt='抗皱活肤驻颜霜' width='100px' height='100px' border='0' /></a>
	 </td></tr>
	<tr><td align='center' width='130px' >
	<a href='http://www.sisley.com.cn/150000.html'><font size='2'>抗皱活肤驻颜霜</font></a><br />
	<a href='http://www.sisley.com.cn/150000.html'><font size='2'>50ml - ￥2,890.00</font></a>
	</td></tr>
	</table>
</td>
<td>
</td>
</tr>
</table>
</td></tr>





<tr>
<td align='center' width='635px'>
<a href='http://www.sisley.com.cn/162300.html'
<img src='http://www.sisley.com.cn/skin/frontend/default/default/images/email-bg.jpg' alt='促销商品通栏Banner' width='635' height='140' border='0'/></a></td>
</tr>
<tr>
<td height='15px'>
<font size='2'><a href='http://www.sisley.com.cn/vs1.html'>全能乳液套装</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='http://www.sisley.com.cn/vs2.html'>花香保湿面膜套装</a></font>
</td>
</tr>
<tr>
<td style='background:#e0e0e0' width='635px'>
<font size='2'>
在希思黎官网您可以尊享：100%正品保证<br />
希思黎官方网站暨网上商城会员热线：4008-208-139(9:00-21:00国定节假日除外)<br />
了解更多信息，请访问帮助中心。请保管您的邮箱，以免他人盗用，如有任何疑问，请查看希思黎会员条款。<br />
请注意：此邮件发送地址仅用于发送邮件，请勿直接回复。如须与我们联系，您可以发送邮件至cs@sisley.com.cn<br />
</font>
</td>
</tr>

</table>";





$FocusEmail->IsBodyHtml=true;

$FocusTask=new StdClass;
$FocusTask->TaskName="batch send php";
$FocusTask->Subject="first subject";
$FocusTask->SenderName="abc";
$FocusTask->SenderEmail="abc@focussend.com";
$FocusTask->ReplyName="reply";
$FocusTask->ReplyEmail="zcz_wn@163.com";
$FocusTask->SendDate=date("Y-m-d\TH-m-s");
//$FocusTask->SendDate="2010-06-04T00:00:00";    

$subject="感谢您购买【希思黎官方网站暨网上商城】商品";

//$FocusReceiver=new StdClass;
$FocusReceiver->Email=$customer->getEmail();

//send one email
$result= $SoapClient->SendOne(array("user"=>$FocusUser,"email"=>$FocusEmail,"subject"=>$subject,"receiver"=>$FocusReceiver));
/*** end edm ***/
}

function getOrderCollection() {
	$targetday = date('Y-m-d',strtotime('-10 days'));
	$OrderArr = array();
	
	$dbname = (string)Mage::getConfig()->getNode('global/resources/default_setup/connection/dbname');
	$username = (string)Mage::getConfig()->getNode('global/resources/default_setup/connection/username');
	$password = (string)Mage::getConfig()->getNode('global/resources/default_setup/connection/password');
	$link = mysql_connect('localhost', $username, $password);
				if (!$link) {
					die('Not connected : ' . mysql_error());
				}//end if
				$db_selected = mysql_select_db($dbname, $link);
				if (!$db_selected) {
					die ('Can\'t use foo : ' . mysql_error());
				}else{
				$_query = sprintf("SELECT orderid FROM arvato_point WHERE date='%s'",
						mysql_real_escape_string($targetday));
						$_result = mysql_query($_query); 
						if (!$_result) {
							$message = 'Invalid query: ' . mysql_error() . "\n";
							$message .= 'Whole query: ' . $_query;
							die($message);
						}
						while ($row = mysql_fetch_assoc($_result)) {
							$OrderArr[] = $row['orderid'];
						}
				}
				mysql_close($link);
	return $OrderArr;
}

$OrderList = getOrderCollection();

foreach ($OrderList as $_order) {
	$order = Mage::getModel('sales/order');
        $order->loadByIncrementId($_order);
	
	$email = $order->getCustomerEmail();
	$customer = Mage::getModel('customer/customer');
	$customer->setWebsiteId(Mage::app()->getStore()->getWebsiteId());
	$customer->loadByEmail($email);
	
	if ($order->getStatus() == 'shipping' || $order->getStatus() == 'complete') {
		SendEmail($customer, $_order);
	}
	//var_dump($customer);
}

?>
