<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="main-container col2-left-layout">
            <div class="main">
                <!--?php echo $this->getChildHtml('breadcrumbs') ?-->
                <div class="col-main" style="float:none;width:auto">
                    <!--?php echo $this->getChildHtml('global_messages') ?-->
					<?php
					
					$cookiename="the_cookie1002";
					
					setcookie($cookiename, 1);
					?>
					<style>
					#register_mail .validation-failed{
						border:0 !important;
						background: none;
						margin-left: 0;
						padding-left: 0;
					}
					#register_mail .validation-advice{
						display:block;
						margin-top:8px;
						color:#FFF69D;
						border:0 !important;
						background: none;
						margin-left: 0;
						font-weight: normal;
						padding-left: 0;
					}
					</style>
					<div style="background:url('/media/registration/register.jpg');padding:0;margin:0;display:block;width:978px;height:612px;">
					<form name="register_mail" id="register_mail" method="post" action="<?php echo $this->getUrl('campaign/index/index'); ?>">
					<div style="display:block;height:614px;float:left;margin-top:0;width:462px;margin-left:0px;cursor:pointer;" onclick="setLocation('http://www.sisley.com.cn/159000.html');">
					
					</div>
					<div style="float:left;margin-top:344px;margin-left:0px;width:380px;">
						<div style="height: 55px;margin-left:108px;text-align:left;" >
							&nbsp;<input type="text" name="popupemail" id="popupemail"  maxlength="50" value="" style="width:220px;border:0;" class="validate-email required-entry" />
							<div class="validation-advice" id="advice-validate-email-popupemail" style="display:none">您输入的E-mail格式错误！</div>
							<div class="validation-advice" id="advice-required-entry-popupemail" style="display:none">请输入Email</div>
						</div>
						<div style="height: 30px;margin-left:108px;text-align:left;">
							&nbsp;<input name="verif_box" class="required-entry" type="text" id="verif_box" style="margin-top:1px;padding:0;width:220px;border:0;" maxlength="4"/>  
						</div>
						<div style="margin-top:0px;margin-left:111px;">
							<img id='verify3'  width='50' height='16' align='absbottom' />
							<a class='next' id="nextverify" style='cursor:pointer;color:#fff;' alt='点击刷新' >换一张</a>
							
							<span id="advice-required-entry-verif_box" style="display:none;color:#FFF69D;font-size: 12px;font-weight: normal;line-height: 13px;">请输入验证码</span>
							<?php 
							//if($this->getRequest()->getParam('error')=='code' || $this->getRequest()->getParam('error')=='code/'){
							?>
								<span style='color:#FFF69D;font-weight:normal;' id="codeerror">&nbsp;</span>
							<?php
						//	}
							?>
						</div>
						<div style="margin-left:45px;color:#fff;height: 14px;line-height: 14px;padding: 0;margin-top:20px;">
							<input type="checkbox" class="required-entry" id="vcheckbox"  name="vcheckbox"  checked="checked" style="height:14px;" />
							
							<img src="/media/registration/note.png" width="236" height="12" border="0" usemap="#Map" />
<map name="Map" id="Map">
  <area shape="rect" coords="90,0,155,22" href="http://www.sisley.com.cn/rules" target="_blank" />
  <area shape="rect" coords="177,-11,242,20" href="http://www.sisley.com.cn/secret" target="_blank" />
</map>


							<span id="advice-required-entry-vcheckbox" style="display:none;color:#FFF69D;font-size: 12px;font-weight: bold;line-height: 13px;">请确认接受条款</span>
						</div>
						<div style="margin-top:30px;margin-left:105px;text-align:center;">
							<button type="submit" class="button" name="send" id="send3"><span style="background:url('/media/registration/registersubmit.png') no-repeat;height:26px;width:69px;padding:0;" ></span></button>
							
							&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
							<a target="_blank" href="http://www.sisley.com.cn/159000.html"  id="send4" /><img src="/media/registration/registerbuy.png" width="69" height="21"></a>
						</div>
					  </div>
					</form>
					</div>
					<script type="text/javascript">
					<!--
	var dataForm2 = new VarienForm('register_mail', true);
jQuery(document).ready(function() {


	jQuery("#verify3").attr("src","/yz.php?"+Math.round(Math.random()*9999));
	jQuery("#nextverify").click(function(){
		jQuery("#verify3").attr("src","/yz.php?"+Math.round(Math.random()*9999));
		return false;
	});

	jQuery("#send3").hover(function(){
		jQuery('#send3 span').css('background','url("/media/registration/registersubmita.png") no-repeat');
	},function(){
		jQuery('#send3 span').css('background','url("/media/registration/registersubmit.png") no-repeat');
	});
	
	jQuery("#send4").hover(function(){
		jQuery('#send4 img').attr('src','/media/registration/registerbuya.png');
	},function(){
		jQuery('#send4 img').attr('src','/media/registration/registerbuy.png');
	});
	
	
	var valid = new Validation('register_mail', {immediate : true});
	if($("popupemail").value){
		valid.validate();
	}
	jQuery('#register_mail').submit(function() {
		var dataForm2 = new VarienForm('register_mail', true);
		if(!valid.validate()){
			return false;
		}
               
		var url = '<?php echo $this->getUrl('campaign/index/verifyajax'); ?>';
		var parameters = {
			popupemail: $("popupemail").value,
			verif_box: $("verif_box").value
		}


		var summary = $('codeerror');
		summary.update('<img src="/media/popup/ajax-loader-tr.gif" height="16" width="16" />');

		new Ajax.Request(url, {
			method: 'post',
			parameters: parameters, 
			onSuccess: function(transport)  {
				if(transport.responseText=="codeerror"){
					$('codeerror').update('验证码输入有误！');
				}else{
					if(transport.responseText=="fail"){
						//$('codeerror').update('fail');
						setLocation('<?php echo $this->getUrl('registerfail'); ?>');
					}else{
						//$('codeerror').update('ok');
						_gaq.push(['_trackPageview', '/2012_registration_page']); 
						setLocation('<?php echo $this->getUrl('registersuccess'); ?>');
					}
				}
			}
		});
		return false;

	  
	  
	  
	  
	  
	  
	});
	
	
}); 
					//-->
					</script>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
