<li class="dob-select">
					<label for="month">出生日期<em>*</em></label>
    <br/>

    <div class="dob-year" style="float:left;width:80px;">
		
		<select <?php if($this->getYear()){ echo 'onfocus="this.defaultIndex=this.selectedIndex;" onchange="this.selectedIndex=this.defaultIndex;" '; } ?> class="validate-select"  name="year" id="year" onchange="getElementById('<?php echo $this->getFieldId('year');?>').value=this.value" style="width:75px;" >
		<option value="">选择年份</option>
		<?php
		for($j=date('Y')-80;$j<=date('Y');$j++)
		{
			$checked='';
			if($this->getYear()==$j){
				$checked='selected="selected"';
			}
			echo "<option value='".$j."' ".$checked.">".$j."</option>";
		}
		?>
		</select>
    </div>
    <div style="width:10px;float:left">-&nbsp;</div>
    <div class="dob-month" style="float:left;width:80px;">
		<select <?php if($this->getMonth()){echo ' onfocus="this.defaultIndex=this.selectedIndex;" onchange="this.selectedIndex=this.defaultIndex;" '; } ?>  name="month" id="month" onchange="getElementById('<?php echo $this->getFieldId('month');?>').value=this.value" style="width:75px;" class="validate-select" >
		<option value=''>选择月份</option>
		<?php  
		
		for($i=1;$i<=12;$i++)
		{
			if($i<10){
				$i="0".$i;
			}
			$checked='';
			if($this->getMonth()==$i){
				$checked='selected="selected"';
			}
			echo "<option value='".$i."' ".$checked.">".$i."</option>";
		}
		?>
		</select>
    </div>
    <div style="width:10px;float:left">-&nbsp;</div>
    <div class="dob-day" style="float:left;width:80px;">
		<select <?php if($this->getDay()){echo ' onfocus="this.defaultIndex=this.selectedIndex;" onchange="this.selectedIndex=this.defaultIndex;" '; } ?> name="day" id="day" onchange="getElementById('<?php echo $this->getFieldId('day');?>').value=this.value" style="width:75px;" class="validate-select" >
		<option value="">选择日期</option>
		<?php
		for($i=1;$i<=31;$i++)
		{
			if($i<10){
				$i="0".$i;
			}
			$checked='';
			if($this->getDay()==$i){
				$checked='selected="selected"';
			}
			echo "<option value='".$i."' ".$checked.">".$i."</option>";
		}
		?>
		</select>
    </div>

    <div class="dob-full" >
        <input type="hidden" id="<?php echo $this->getFieldId('dob')?>" name="<?php echo $this->getFieldName('dob')?>" />
    </div>
    <div style="opacity: 0.999999; display:none;" class="validation-advice">生日是必填项。</div>
	
	<div style="clear:both;line-height:32px;">一经填写不可修改，请准确填写</div>
</li>



