<div class="newcz-clo2 caizhuangbg">
<select style="font-size:12px;font-family:宋体;" onchange="window.location.href=this.value" id="recherche_par_besoin" name="recherche_par_besoin">

<option>您正在寻找的彩妆是..</option>
<option value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>cosmetics_1">控制面部泛油光</option>
<option value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>cosmetics_2">淡化黑眼圈</option>
<option value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>cosmetics_3">均匀肤色</option>
<option value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>cosmetics_4">健康光泽</option>
<option value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>cosmetics_5">提亮颧骨处</option>
<option value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>cosmetics_6">提亮暗淡肤色</option>
<option value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>cosmetics_7">自然清新</option>
<option value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>cosmetics_8">精致成熟</option>
<option value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>cosmetics_9">派对时刻</option>
</select>
</div>