<div class="LeftQuest">







<div class="view-key">

	<h5>关键字</h5>
<ul class="key-ul">
 <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>catalogsearch/result/?q=美白"><li>美白</li></a>
 <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>catalogsearch/result/?q=防晒"><li>防晒</li></a>
 <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>catalogsearch/result/?q=控油"><li>控油</li></a>
 <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>catalogsearch/result/?q=抗老"><li>抗老</li>	</a>
 <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>catalogsearch/result/?q=保湿"><li>保湿</li></a>
 <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>catalogsearch/result/?q=香水"><li>香水</li></a>
 

</ul>
 </div>
</div>