<div class="newclo2 NewBg">
<select style="font-size:12px;font-family:宋体;" onchange="window.location.href=this.value" id="recherche_par_besoin" name="recherche_par_besoin">

<option>根据您的要求搜索:</option>
<option value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>diagnostic_beaute_male_1">每日平衡肌肤</option>
<option value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>diagnostic_beaute_male_2">剃须前的肌肤护理</option>
<option value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>diagnostic_beaute_male_3">舒缓剃须刺激</option>
<option value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>diagnostic_beaute_male_4">补水</option>
<option value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>diagnostic_beaute_male_5">淡化疲惫痕迹</option>
<option value="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>diagnostic_beaute_male_6">抑止过多皮脂</option>
</select>
</div>