<div align="center">
<h3 class="icon-head"><u><?php echo Mage::helper('attributemanager')->__('Choose attributes to manage') ?></u></h3>
<br/><br/>
<h3 class="icon-head">
<a href="<?php echo $this->getUrl('attributemanager/index/category/filter//');?>"><?php echo Mage::helper('attributemanager')->__('Categories attributes') ?></a>
<br/>
<a href="<?php echo $this->getUrl('attributemanager/index/customer/filter//');?>"><?php echo Mage::helper('attributemanager')->__('Customers attributes') ?></a>
<br/>
<a href="<?php echo $this->getUrl('attributemanager/index/address/filter//');?>"><?php echo Mage::helper('attributemanager')->__('Customer\'s address attributes') ?></a></h3>
</div> 
