<?php
	function checkSaleable($_product, $elenment) {  //check child product qty
		$assoc_products = array();
		$associated_prods = $_product->getTypeInstance()->getUsedProducts();
		foreach ($associated_prods as $assoc_product) {
			//Creates the saleable associated products object array.
			if ($assoc_product->isSaleable()) {
				$OptionValue = $assoc_product[$elenment];
				$Id = $assoc_product->getId();
				$child_product = Mage::getModel('catalog/product')->load($Id);
				$Qty = Mage::getModel('cataloginventory/stock_item')->loadByProduct($child_product)->getQty();
				$assoc_products[$OptionValue] = $Qty;
				//$assoc_products[] = $assoc_product;
			}
		}
		return $assoc_products;

	}
    
    































?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('') ?></p>
<?php else: ?>

<div class="search-top">
<?php
if($_POST){
foreach ($_productCollection as $_product){
$_Product = Mage::getModel('catalog/product')->loadByAttribute('sku', $_product->getSku());
$_CategoryIds = $_Product->getCategoryIds();
if(in_array($_POST['categoryname'],$_CategoryIds)) {
$All[] = $_product;
//var_dump($_product->getName());
}
$TotalNum = count($All);
$KeyWord = $this->helper('catalogsearch')->getEscapedQueryText().'”+“'.Mage::getModel('catalog/category')->setStoreId(Mage::app()->getStore()->getId())->load($_POST['categoryname'])->getName();
}
}else{
$TotalNum = $_productCollection->count();
$KeyWord = $this->helper('catalogsearch')->getEscapedQueryText();
}
?>
<div class="resultSearch"> <?php echo $this->__('搜索到'.$TotalNum.'条关于“'.$KeyWord.'”匹配的结果。'); ?></div>
</div>
<form action="" id="search_form" method="post">
<div class="serch-middle">
	<div class="serch-middlie-tit">肌肤问题</div>
	 <div class="serch-middlie-ul">
	 <ul>
	 	
		 <div class="search-top">
		 
		 <script type="text/javascript">
		 function post(categoryname){
		 $('categoryname').value = categoryname;
		 //alert(categoryname);
		 }
		
		 function setHidden(limit, categoryname){
		 $('limit').value = limit;
		 $('categoryname').value = categoryname;
		 //alert(limit);
		 }
		
		 var Form = new VarienForm('search_form');
                 Form.submit = function(){
                            this.form.submit();
           	 }.bind(Form);
		 </script>
		 	<input type="hidden" name="categoryname" id='categoryname'/>
		 	
		 	<input type="hidden" name="limit" id='limit'/>
			<?php
			$catId = '240';
			$SearchCat = Mage::getModel('catalog/category')->load($catId);
			$childrenIdArray = explode(',', $SearchCat->getChildren());
			//var_dump($childrenIdArray);
			foreach($childrenIdArray as $key => $value) {
			$children = Mage::getModel('catalog/category')->load($value);
			//var_dump($children);
			$childrens[] = $children->getId();
			}
			foreach($_productCollection as $_product){
			$product = Mage::getModel('catalog/product')->loadByAttribute('sku', $_product->getSku());
			$categoryIds = $product->getCategoryIds();
				foreach($categoryIds as $categoryId) {  
				$Category = Mage::getModel('catalog/category') 
				->setStoreId(Mage::app()->getStore()->getId()) 
				->load($categoryId);
				//var_dump($categoryId.'@@'.$Category->getName().'<br>');
					if((in_array($Category->getId(),$childrens))&&(!array_key_exists($categoryId,$Already))) {
					$CategoryName['url'] = $Category->getId();
					$CategoryName['name'] = $Category->getName();
					$categoryname = $Category->getId();
					$Already[$categoryname] = $CategoryName;
					
					?>
					
					<?php
					}
				}
				//var_dump($Already);
			}
			foreach($Already as $key => $val) {
			//var_dump($val);
			?>
			<li style="cursor: pointer; padding-left:10px; width:120px;"  onclick="post(this.id);Form.submit()" id="<?php echo $val['url']; ?>"><?php echo $val['name']; ?></li>
			<?php
			}
			//var_dump($CategoryNames);
			?>
                 </div>
		
	 </ul>
	 </div>
</div>

<div class="category-products">
    
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php echo $this->getToolbarHtml() ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" target="_blank"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" target="_blank"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->isSaleable()): ?>
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="link-more"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
    
    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>

    <?php else: ?>

    <?php // Grid Mode ?>
    <?php if($_POST) { ?>
    <!-- advance search -->
    	<?php //var_dump($_POST['categoryname']); ?>
   	<?php $_collectionSize = $_productCollection->count() ?>
   	<?php $_columnCount =4 ?>
   	<?php
   	foreach ($_productCollection as $_product) {
   	$_Product = Mage::getModel('catalog/product')->loadByAttribute('sku', $_product->getSku());
    	$_CategoryIds = $_Product->getCategoryIds();
   	if(in_array($_POST['categoryname'],$_CategoryIds)) {
   	$_All[] = $_Product;
   	}
   	}
   	$Num = count($_All);
   	//var_dump($Num);
   	?>
   	<div class="toolbar">
	    <div class="pager">
		<p class="amount">
		    <?php if($this->getLastPageNum()>1): ?>
		        <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $Num) ?>
		    <?php else: ?>
		        <strong><?php echo $this->__('%s Item(s)', $Num) ?></strong>
		    <?php endif; ?>
		</p>

		<div class="limiter">
		    <label><?php echo $this->__('Show') ?></label>
		    <select onchange='setHidden(this.id, this.value);Form.submit()'>
		    <option id="top100" value="<?php echo $_POST['categoryname'] ?>">100</option>
		    <option id="topall" value="<?php echo $_POST['categoryname'] ?>">所有</option>
		    </select> <?php echo $this->__('per page') ?>
		</div>

		<?php echo $this->getPagerHtml() ?>
	    </div>
	</div>
    	<?php $i=0; foreach ($_productCollection as $_product): ?>
    	<?php
    	$_Product = Mage::getModel('catalog/product')->loadByAttribute('sku', $_product->getSku());
    	$_CategoryIds = $_Product->getCategoryIds();
				//var_dump($_CategoryIds);
	if(in_array($_POST['categoryname'],$_CategoryIds)) {
    	?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid1">
        <?php endif ?>
            <li class="itemList">
               <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" target="_blank"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(166,176); ?>" width="166" height="176" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" target="_blank"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
              
				<div class="Listrongliang">
				<span><?php echo $_helper->productAttribute($_product, $_product->getRongliang (), 'rongliang ') ?></span>
				</div>
				<?php if($_product->getTypeId() =='configurable') { ?>
				<?php $_attributes = $_product->getTypeInstance(true)->getConfigurableAttributes($_product); ?>
				   <?php foreach($_attributes as $_attribute) { ?>
				   <?php //var_dump($_attribute);
				   //exit;
				   ?>
					  <?php if($_attribute->getAttributeId() == '145') { ?>
										 <!-- get options -->
										<?php //echo $_product->isSaleable() ?>
										<?php //echo count($_attributes) ?>
										
										<?php
										//$ChildProducts = checkSaleable($_product);
										//var_dump($ChildProducts);
										//exit;
										?>
										
										<?php if ($_product->isSaleable() && count($_attributes)):?>
										<dl style="display: none ">
										
										<dt><label><?php echo $_attribute->getLabel() ?><span class="required">&nbsp;*</span></label></dt>
										<dd <?php if ($_attribute->decoratedIsLast){?> class="last" <?php }?>>
										<select
										name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]"
										id="attribute<?php echo $_attribute->getAttributeId() ?>"
										class="required-entry super-attribute-select">
										</select></dd>
										
										</dl>
										<?php //echo '123'; ?>
										<input type="hidden" name="jiage" value="on"/>
										<input type="hidden" name="product" value="<?php echo $_product->getId() ?>"/>
										<input type="hidden" name="qty" value="1"/>
										<input type="hidden" name="related_product" value=""/>
										<input type="hidden" name="type" value="0" id='buttontype'/>
										
										<?php //echo $_attribute->getAttributeId() ?>
										
										<script type="text/javascript">
										function setPoint(optionid, proid) {
										var oid = proid + 'op145';
										var pid = proid + 'productid';
											$(oid).value = optionid;
											$(pid).value = proid;
											//alert(optionid);
										}
										</script>
										<?php //echo '123'; ?>
										<?php 
										$attribute = Mage::getModel('eav/config')->getAttribute('catalog_product', 'rongliang');
										$allPoints = $attribute->getSource()->getAllOptions(true, true);
										$pointcolumn = count($allPoints);
										$IdArr = array();
										$ProductInfo = Mage::getModel('catalog/product')->load($productId);
										$dbname = (string)Mage::getConfig()->getNode('global/resources/default_setup/connection/dbname');
										$username = (string)Mage::getConfig()->getNode('global/resources/default_setup/connection/username');
										$password = (string)Mage::getConfig()->getNode('global/resources/default_setup/connection/password');
										$product_id = $_product->getId();
										Mage::app();
										$link = mysql_connect('localhost', $username, $password);
										if (!$link) {
										die('Not connected : ' . mysql_error());
										}//end if
										$db_selected = mysql_select_db($dbname, $link);
										if (!$db_selected) {
										die ('Can\'t use foo : ' . mysql_error());
										}else{
										//echo $product_id;
										
										$query = sprintf("SELECT product_super_attribute_id FROM catalog_product_super_attribute WHERE product_id='%s' AND attribute_id='145'",
										mysql_real_escape_string($product_id));
										//echo $query;
										$result = mysql_query($query); 
										if (!$result) {
										$message = 'Invalid query: ' . mysql_error() . "\n";
										$message .= 'Whole query: ' . $query;
										die($message);
										}//end if 
										while ($row = mysql_fetch_assoc($result)) {
										$ProAttId = $row['product_super_attribute_id'];
										}
										//var_dump($ProAttId);
										?>
										<?php //echo '456'; ?>
										<div class='size-color'>
										<div style="width: 195px;" id="PointDiv">
										
										<select onchange="setPoint(this.options[this.options.selectedIndex].value, <?php echo $product_id; ?>)">
										<?php foreach ($allPoints as $point) : ; $pointlabel=$point['label']; $pointid=$point['value'];  ?>
										<?php if($pointlabel != NULL) { ?>
										
										
										<?php
										$product_super_attribute_id = $ProAttId;
										$value_index = $point['value'];
										
										$query = sprintf("SELECT pricing_value FROM catalog_product_super_attribute_pricing WHERE product_super_attribute_id='%s' AND value_index='%s'",
											mysql_real_escape_string($product_super_attribute_id),
											mysql_real_escape_string($value_index));
										
										$result = mysql_query($query); 
										if (!$result) {
										$message = 'Invalid query: ' . mysql_error() . "\n";
										$message .= 'Whole query: ' . $query;
										die($message);
										}//end if 
										while ($row = mysql_fetch_assoc($result)) {
										$PriceValue = $row['pricing_value'];
										}
										
										//$PriceValue = 0;
										if($PriceValue != 0) {
										$PriceValue = number_format($PriceValue, 2, '.', '');
										$IdArr[] = $pointid;
										?>
										<?php $PriceValue = number_format($PriceValue, 2, '.', ''); ?>
										<?php
										$ChildProducts = checkSaleable($_product, 'rongliang');
										if ($ChildProducts[$pointid] != NULL) {
										?>
										<option id="<?php echo $pointid; ?>" name="jiage" value="<?php echo $pointid; ?>" ><?php echo $pointlabel." - ￥".$PriceValue; ?></option>
										<?php }else{ ?>
										<!--<option id="<?php //echo $pointid; ?>" style="display:none; visible:hidden; "  name="jiage" value="<?php //echo $pointid; ?>" ><?php //echo $pointlabel." - ￥".$PriceValue; ?>(已售罄)</option>-->
										<?php } ?>
										
										<?php
										}
										$PriceValue = 0;
										?>
										<?php } ?>
										<?php endforeach ;?>
										</select>
										
										</div>

									
										</div>

										<?php
										}
										mysql_close($link);
										?>
										
										<input id="<?php echo $_product->getId() ?>op145" type="hidden" name="super_attribute[145]" value="<?php echo $IdArr['0'] ?>"/>
										
										<?php endif;?>
										<div class="clear"></div>
										<!-- end get options -->		
								<?php } ?>
				<?php if($_attribute->getAttributeId() == '80') { ?>
								<!-- get options -->
					<?php //echo $_product->isSaleable() ?>
					<?php //echo count($_attributes) ?>
					<?php if ($_product->isSaleable() && count($_attributes)):?>
					<dl style="display: none ">
					
					<dt><label><?php echo $_attribute->getLabel() ?><span class="required">&nbsp;*</span></label></dt>
					<dd <?php if ($_attribute->decoratedIsLast){?> class="last" <?php }?>>
					<select
					name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]"	id="attribute<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select">
					</select></dd>
					
					</dl>
					<?php //echo '123'; ?>
					<input type="hidden" name="jiage" value="on"/>
		    		<input type="hidden" name="product" value="<?php echo $_product->getId() ?>"/>
					<input type="hidden" name="qty" value="1"/>
					<input type="hidden" name="related_product" value=""/>
					<input type="hidden" name="type" value="0" id='buttontype'/>
					<input id="op<?php echo $_attribute->getAttributeId() ?>" type="hidden" name="super_attribute[80]" value="16"/>	
					<?php //echo $_attribute->getAttributeId() ?>
					
						<script type="text/javascript">
						function setPoint(optionid, proid) {
						var oid = proid + 'op80';
						var pid = proid + 'productid';
							$(oid).value = optionid;
							$(pid).value = proid;
							//alert(optionid);
						}
						</script>
					<?php //echo '123'; 
					//$ChildProducts = checkSaleable($_product, 'color');
					//var_dump($ChildProducts);
					?>
					<?php 
					$attribute = Mage::getModel('eav/config')->getAttribute('catalog_product', 'color');
					$allPoints = $attribute->getSource()->getAllOptions(true, true);

					$pointcolumn = count($allPoints);
					$IdArr = array();
					$ProductInfo = Mage::getModel('catalog/product')->load($productId);
					$dbname = (string)Mage::getConfig()->getNode('global/resources/default_setup/connection/dbname');
					$username = (string)Mage::getConfig()->getNode('global/resources/default_setup/connection/username');
					$password = (string)Mage::getConfig()->getNode('global/resources/default_setup/connection/password');
					$product_id = $_product->getId();
					Mage::app();
					$link = mysql_connect('localhost', $username, $password);
					if (!$link) {
					die('Not connected : ' . mysql_error());
					}//end if
					$db_selected = mysql_select_db($dbname, $link);
					if (!$db_selected) {
					die ('Can\'t use foo : ' . mysql_error());
					}else{
					//echo $product_id;
					
					$query = sprintf("SELECT product_super_attribute_id FROM catalog_product_super_attribute WHERE product_id='%s' AND attribute_id='80'",
					mysql_real_escape_string($product_id));
					$result = mysql_query($query); 
					if (!$result) {
					$message = 'Invalid query: ' . mysql_error() . "\n";
					$message .= 'Whole query: ' . $query;
					die($message);
					}//end if 
					while ($row = mysql_fetch_assoc($result)) {
					$ProAttId = $row['product_super_attribute_id'];
					}
					
					?>
					<?php 	//echo '456'; ?>
					<div class='size-color'>
					<div style="width: 195px;" id="PointDiv">
					
					<select onchange="setPoint(this.options[this.options.selectedIndex].value, <?php echo $product_id; ?>)">
					<?php foreach ($allPoints as $point) : ; $pointlabel=$point['label']; $pointid=$point['value'];  ?>
					<?php if($pointlabel != NULL) { ?>
					
					
					<?php
					$product_super_attribute_id = $ProAttId;
					$value_index = $point['value'];
					
					$query = sprintf("SELECT pricing_value FROM catalog_product_super_attribute_pricing WHERE product_super_attribute_id='%s' AND value_index='%s'",
				        mysql_real_escape_string($product_super_attribute_id),
				        mysql_real_escape_string($value_index));
					$result = mysql_query($query); 
					if (!$result) {
					$message = 'Invalid query: ' . mysql_error() . "\n";
					$message .= 'Whole query: ' . $query;
					die($message);
					}//end if 
					while ($row = mysql_fetch_assoc($result)) {
					$PriceValue = $row['pricing_value'];
					
					}
					
					//$PriceValue = 0;
					if($PriceValue != 0) {
					$PriceValue = number_format($PriceValue, 2, '.', '');
					$IdArr[] = $pointid;
					?>
					<?php $PriceValue = number_format($PriceValue, 2, '.', ''); ?>
					<?php
					$ChildProducts = checkSaleable($_product, 'color');
					//var_dump($ChildProducts);
					
					if ($ChildProducts[$pointid] != NULL) {
					?>
					<option id="<?php echo $pointid; ?>" name="jiage" value="<?php echo $pointid; ?>" ><?php echo $pointlabel." - ￥".$PriceValue; ?></option>
					<?php }else{ ?>
					<!--<option id="<?php //echo $pointid; ?>" name="jiage" value="<?php //echo $pointid; ?>" style="display:none;" ><?php //echo $pointlabel." - ￥".$PriceValue; ?>(已售罄)</option>-->
					<?php } ?>
					<?php
					}
					$PriceValue = 0;
					?>
					<?php } ?>
					<?php endforeach ;?>
					</select>
					
					</div>

				
					</div>

					<?php
					}
					mysql_close($link);
					?>
					<input id="<?php echo $_product->getId() ?>op80" type="hidden" name="super_attribute[80]" value="<?php echo $IdArr['0'] ?>"/>
					
					<?php endif;?>
					<div class="clear"></div>
					<!-- end get options -->
								
						<?php } ?>
								
					 <?php } ?>
				<?php }else{ ?>
				<?php echo $this->getPriceHtml($_product, true) ?>
				<?php } ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><span><span><?php echo $this->__('') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                  
                </div>
			
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php } ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>    
    <div class="toolbar-bottom">
	<!--<div class="toolbar">
	    <div class="pager">
		<p class="amount">
		    <?php //if($this->getLastPageNum()>1): ?>
		        <?php //echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $Num) ?>
		    <?php //else: ?>
		        <strong><?php echo $this->__('%s Item(s)', $Num) ?></strong>
		    <?php //endif; ?>
		</p>

		<div class="limiter">
		    <label><?php //echo $this->__('Show') ?></label>
		    <select onchange='setHidden(this.id, this.value);Form.submit()'>
		    <option id="foot100" value="<?php //echo $_POST['categoryname'] ?>">100</option>
		    <option id="footall" value="<?php //echo $_POST['categoryname'] ?>">所有</option>
		    </select> <?php //echo $this->__('per page') ?>
		</div>
		<?php //echo $this->getPagerHtml() ?>
	    </div>
	</div>-->
    </div>
    <!-- advance search -->
    <?php }else{ ?>
    <!-- search result -->
    <?php echo $this->getToolbarHtml() ?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount =4 ?>
	 
	
    <?php $i=0; foreach ($_productCollection as $_product): ?>
	<?php if($_product->getTypeId() =='configurable') { ?>
	<?php $_attributes = $_product->getTypeInstance(true)->getConfigurableAttributes($_product); ?>
	
    <?php foreach($_attributes as $_attribute) { ?>
	<?php //var_dump($_attribute->getAttributeId()); ?>
    <?php if($_attribute->getAttributeId() == '145') { ?>
	<?php //echo '123'; ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid1">
        <?php endif ?>
            <li class="itemList">
               <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" target="_blank"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(166,176); ?>" width="166" height="176" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" target="_blank"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
				
				
				<!-- get options -->
					<?php //echo $_product->isSaleable() ?>
					<?php //echo count($_attributes) ?>
					<?php if ($_product->isSaleable() && count($_attributes)):?>
					<dl style="display: none ">
					
					<dt><label><?php echo $_attribute->getLabel() ?><span class="required">&nbsp;*</span></label></dt>
					<dd <?php if ($_attribute->decoratedIsLast){?> class="last" <?php }?>>
					<select
					name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]"
					id="attribute<?php echo $_attribute->getAttributeId() ?>"
					class="required-entry super-attribute-select">
					</select></dd>
					
					</dl>
					<?php //echo '123'; ?>
					<input type="hidden" name="jiage" value="on"/>
		    			<input type="hidden" name="product" value="<?php echo $_product->getId() ?>"/>
					<input type="hidden" name="qty" value="1"/>
					<input type="hidden" name="related_product" value=""/>
					<input type="hidden" name="type" value="0" id='buttontype'/>
					<input id="op<?php echo $_attribute->getAttributeId() ?>" type="hidden" name="super_attribute[145]" value="16"/>	
					<?php //echo $_attribute->getAttributeId() ?>
					
					<script type="text/javascript">
					function SelectPoint(pointid) {
					    $('op145').value = pointid;
					   // alert(pointid);
					}
					</script>
					<?php //echo '123'; ?>
					<?php 
					$attribute = Mage::getModel('eav/config')->getAttribute('catalog_product', 'rongliang');
					$allPoints = $attribute->getSource()->getAllOptions(true, true);
					$pointcolumn = count($allPoints);
					$ProductInfo = Mage::getModel('catalog/product')->load($productId);
					$dbname = (string)Mage::getConfig()->getNode('global/resources/default_setup/connection/dbname');
					$username = (string)Mage::getConfig()->getNode('global/resources/default_setup/connection/username');
					$password = (string)Mage::getConfig()->getNode('global/resources/default_setup/connection/password');
					$product_id = $_product->getId();
					Mage::app();
					$link = mysql_connect('localhost', $username, $password);
					if (!$link) {
					die('Not connected : ' . mysql_error());
					}//end if
					$db_selected = mysql_select_db($dbname, $link);
					if (!$db_selected) {
					die ('Can\'t use foo : ' . mysql_error());
					}else{
					//echo $product_id;
					
					$query = sprintf("SELECT product_super_attribute_id FROM catalog_product_super_attribute WHERE product_id='%s' AND attribute_id='145'",
					mysql_real_escape_string($product_id));
					$result = mysql_query($query); 
					if (!$result) {
					$message = 'Invalid query: ' . mysql_error() . "\n";
					$message .= 'Whole query: ' . $query;
					die($message);
					}//end if 
					while ($row = mysql_fetch_assoc($result)) {
					$ProAttId = $row['product_super_attribute_id'];
					}
					
					?>
					<?php //echo '456'; ?>
					<div class='size-color'>
					<div style="width: 195px;" id="PointDiv">
					
					<select onchange="SelectPoint(this.options[this.options.selectedIndex].value)">
					<?php foreach ($allPoints as $point) : ; $pointlabel=$point['label']; $pointid=$point['value'];  ?>
					<?php if($pointlabel != NULL) { ?>
					<!--<div class="shirt_point fL" onclick="SelectPoint(this.id);"
						id="<?php echo $pointid; ?>" title="" style="cursor: pointer;">
						
						<input id="PointName<?php echo $pointid; ?>" type="radio" name="jiage"><?php echo $pointlabel; ?></input>
						<span style="display: none;" id="PointNameSpan<?php echo $pointid; ?>"><?php echo $pointlabel; ?></span>
					</div>-->
					
					<!--<option id="<?php echo $pointid; ?>"  onchange="SelectPoint(this.id);" name="jiage"><?php echo $pointlabel; ?></option>-->
					
					<?php
					$product_super_attribute_id = $ProAttId;
					$value_index = $point['value'];
					
					$query = sprintf("SELECT pricing_value FROM catalog_product_super_attribute_pricing WHERE product_super_attribute_id='%s' AND value_index='%s'",
				        mysql_real_escape_string($product_super_attribute_id),
				        mysql_real_escape_string($value_index));
					$result = mysql_query($query); 
					if (!$result) {
					$message = 'Invalid query: ' . mysql_error() . "\n";
					$message .= 'Whole query: ' . $query;
					die($message);
					}//end if 
					while ($row = mysql_fetch_assoc($result)) {
					$PriceValue = $row['pricing_value'];
					
					}
					
					//$PriceValue = 0;
					if($PriceValue != 0) {
					$PriceValue = number_format($PriceValue, 2, '.', '');
					?>
					<?php $PriceValue = number_format($PriceValue, 2, '.', ''); ?>
					<option id="<?php echo $pointid; ?>" name="jiage" value="<?php echo $pointid; ?>" a="a"><?php echo $pointlabel." - ￥".$PriceValue; ?></option>
					
					<?php
					}
					$PriceValue = 0;
					?>
					<?php } ?>
					<?php endforeach ;?>
					</select>
					
					</div>

					<script>
					
					var pointidLast ='PointId' + <?php echo $pointid; ?>;
					SelectPoint(pointidLast);
					</script>
					</div>

					<?php
					}
					mysql_close($link);
					?>
					<?php endif;?>
					<div class="clear"></div>
					<!-- end get options -->
				
				
                <?php /*if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; */?>
				<div class="Listrongliang">
				<span><?php echo $_helper->productAttribute($_product, $_product->getRongliang (), 'rongliang ') ?></span>
				</div>
                <?php //echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><span><span><?php echo $this->__('') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <!--<ul class="add-to-links">
                        <?php/* if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif;*/ ?>
                    </ul>-->
                </div>
			
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
		
		<?php
		} 
		?>
		<!-- Add Another attribute -->
		
		 <?php if($_attribute->getAttributeId() == '80') { ?>
	<?php //echo '123'; ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid1">
        <?php endif ?>
            <li class="itemList">
               <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" target="_blank"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(166,176); ?>" width="166" height="176" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" target="_blank"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
				
				
				<!-- get options -->
					<?php //echo $_product->isSaleable() ?>
					<?php //echo count($_attributes) ?>
					<?php if ($_product->isSaleable() && count($_attributes)):?>
					<dl style="display: none ">
					
					<dt><label><?php echo $_attribute->getLabel() ?><span class="required">&nbsp;*</span></label></dt>
					<dd <?php if ($_attribute->decoratedIsLast){?> class="last" <?php }?>>
					<select
					name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]"	id="attribute<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select">
					</select></dd>
					
					</dl>
					<?php //echo '123'; ?>
					<input type="hidden" name="jiage" value="on"/>
		    		<input type="hidden" name="product" value="<?php echo $_product->getId() ?>"/>
					<input type="hidden" name="qty" value="1"/>
					<input type="hidden" name="related_product" value=""/>
					<input type="hidden" name="type" value="0" id='buttontype'/>
					<input id="op<?php echo $_attribute->getAttributeId() ?>" type="hidden" name="super_attribute[80]" value="16"/>	
					<?php //echo $_attribute->getAttributeId() ?>
					
					<script type="text/javascript">
					function SelectPoint(pointid) {
					    $('op80').value = pointid;
					   // alert(pointid);
					}
					</script>
					<?php //echo '123'; ?>
					<?php 
					$attribute = Mage::getModel('eav/config')->getAttribute('catalog_product', 'color');
					$allPoints = $attribute->getSource()->getAllOptions(true, true);
					$pointcolumn = count($allPoints);
					$ProductInfo = Mage::getModel('catalog/product')->load($productId);
					$dbname = (string)Mage::getConfig()->getNode('global/resources/default_setup/connection/dbname');
					$username = (string)Mage::getConfig()->getNode('global/resources/default_setup/connection/username');
					$password = (string)Mage::getConfig()->getNode('global/resources/default_setup/connection/password');
					$product_id = $_product->getId();
					Mage::app();
					$link = mysql_connect('localhost', $username, $password);
					if (!$link) {
					die('Not connected : ' . mysql_error());
					}//end if
					$db_selected = mysql_select_db($dbname, $link);
					if (!$db_selected) {
					die ('Can\'t use foo : ' . mysql_error());
					}else{
					//echo $product_id;
					
					$query = sprintf("SELECT product_super_attribute_id FROM catalog_product_super_attribute WHERE product_id='%s' AND attribute_id='80'",
					mysql_real_escape_string($product_id));
					$result = mysql_query($query); 
					if (!$result) {
					$message = 'Invalid query: ' . mysql_error() . "\n";
					$message .= 'Whole query: ' . $query;
					die($message);
					}//end if 
					while ($row = mysql_fetch_assoc($result)) {
					$ProAttId = $row['product_super_attribute_id'];
					}
					
					?>
					<?php //echo '456'; ?>
					<div class='size-color'>
					<div style="width: 195px;" id="PointDiv">
					
					<select onchange="SelectPoint(this.options[this.options.selectedIndex].value)">
					<?php foreach ($allPoints as $point) : ; $pointlabel=$point['label']; $pointid=$point['value'];  ?>
					<?php if($pointlabel != NULL) { ?>
					<!--<div class="shirt_point fL" onclick="SelectPoint(this.id);"
						id="<?php echo $pointid; ?>" title="" style="cursor: pointer;">
						
						<input id="PointName<?php echo $pointid; ?>" type="radio" name="jiage"><?php echo $pointlabel; ?></input>
						<span style="display: none;" id="PointNameSpan<?php echo $pointid; ?>"><?php echo $pointlabel; ?></span>
					</div>-->
					
					<!--<option id="<?php echo $pointid; ?>"  onchange="SelectPoint(this.id);" name="jiage"><?php echo $pointlabel; ?></option>-->
					
					<?php
					$product_super_attribute_id = $ProAttId;
					$value_index = $point['value'];
					
					$query = sprintf("SELECT pricing_value FROM catalog_product_super_attribute_pricing WHERE product_super_attribute_id='%s' AND value_index='%s'",
				        mysql_real_escape_string($product_super_attribute_id),
				        mysql_real_escape_string($value_index));
					$result = mysql_query($query); 
					if (!$result) {
					$message = 'Invalid query: ' . mysql_error() . "\n";
					$message .= 'Whole query: ' . $query;
					die($message);
					}//end if 
					while ($row = mysql_fetch_assoc($result)) {
					$PriceValue = $row['pricing_value'];
					
					}
					
					//$PriceValue = 0;
					if($PriceValue != 0) {
					$PriceValue = number_format($PriceValue, 2, '.', '');
					?>
					<?php $PriceValue = number_format($PriceValue, 2, '.', ''); 
					
						$ChildProducts = checkSaleable($_product, 'color');
						if (isset($ChildProducts[$pointid]) ) {
							if($ChildProducts[$pointid]>0){
					?>
					<option id="<?php echo $pointid; ?>" name="jiage" value="<?php echo $pointid; ?>" b="b" ><?php echo $pointlabel." - ￥".$PriceValue; ?></option>
					
					<?php
							}
						}
					}
					$PriceValue = 0;
					?>
					<?php } ?>
					<?php endforeach ;?>
					</select>
					
					</div>

					<script>
					
					var pointidLast ='PointId' + <?php echo $pointid; ?>;
					SelectPoint(pointidLast);
					</script>
					</div>

					<?php
					}
					mysql_close($link);
					?>
					<?php endif;?>
					<div class="clear"></div>
					<!-- end get options -->
				
				
                <?php /*if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; */?>
				<div class="Listrongliang">
				<span><?php echo $_helper->productAttribute($_product, $_product->getRongliang (), 'rongliang ') ?></span>
				</div>
                <?php //echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><span><span><?php echo $this->__('') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <!--<ul class="add-to-links">
                        <?php/* if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif;*/ ?>
                    </ul>-->
                </div>
			
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
		
		<?php
		} 
		?>
		
		
		<?php 
		}
		}else{
		?>
		<!-- simple product -->
		

		        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid1">
        <?php endif ?>
            <li class="itemList">
               <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" target="_blank"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(166,176); ?>" width="166" height="176" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h5><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" target="_blank"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h5>			
				
                
				<?php if($_product->getCapacity()) { ?>
				<div class="Listrongliang">
				<span><?php echo $_helper->productAttribute($_product, $_product->getCapacity(), 'capacity') ?></span><span>-</span>
				</div>
				<?php } ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><span><span><?php echo $this->__('') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
			
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
		
		<?php } ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <!-- end search result -->
   
    <?php } ?>
    <?php endif; ?>

    	
</div>
</form>
<?php endif; ?>
 <div class="toolbar-bottom">
        <?php //echo $this->getToolbarHtml() ?>
    </div>


<div class="searchbottom">	
		<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>skin.html">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cataserchdown')->toHtml(); ?>
		</a>
		</div>

